package com.aquagreen.config;
import com.aquagreen.model.*;
import com.aquagreen.repository.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

@Component @RequiredArgsConstructor @Slf4j
public class DataSeeder implements CommandLineRunner {
    private final ProductRepository productRepo;
    private final ServiceItemRepository serviceRepo;
    private final CustomerRepository customerRepo;
    private final LeadRepository leadRepo;
    private final EnquiryRepository enquiryRepo;
    private final EmployeeRepository employeeRepo;
    private final SaleRepository saleRepo;
    private final ServiceRequestRepository serviceRequestRepo;
    private final QuotationRepository quotationRepo;
    private final StockItemRepository stockRepo;
    private final BlogRepository blogRepo;
    private final GalleryRepository galleryRepo;
    private final AwardRepository awardRepo;

    @Override
    public void run(String... args) {
        seedProducts(); seedServices(); seedGallery(); seedAwards();
        seedEmployees(); seedStock(); seedBlogs();
        // NOTE: seedCustomers(), seedLeads(), seedEnquiries(), seedSales(),
        // seedServiceRequests(), and seedQuotations() are deliberately NOT
        // called — they only ever generated fake demo records (Rajesh Kumar,
        // Priya Sundaram, etc.). Real customer/lead/sale/service data now
        // comes from the actual business (website submissions, admin entry,
        // and the legacy data import tools) — this app should never
        // auto-generate business records again, even on a fresh database.
        log.info("=== AGA Data Loaded ===");
    }

        void seedProducts() {
        if (productRepo.count() > 0) return;
        productRepo.saveAll(List.of(
            // ── AQUA BRAND DOMESTIC RO PURIFIERS (from price list) ──────────
            Product.builder().name("AQUA CLEAN WATER").description("Entry-level domestic RO purifier with multi-stage filtration. Removes bacteria, viruses, heavy metals and TDS. Compact wall-mount design. Available in RO, UV, RO+UV, RO+UV+UF, RO+UV+UF+TDS, and RO+Alkaline configurations.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("Multi-stage purification,Wall mountable,Auto shutoff,LED indicator,1 year warranty").imageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Clean Water RO Purifier - Aqua Green Agencies Coimbatore").stock(10).minStock(3).displayOrder(1).active(true).build(),
            Product.builder().name("AQUA GRAND").description("Popular domestic RO purifier from Aqua Tech series. Multi-stage purification with optional UV and alkaline filter. Suitable for all water conditions. Available with 9 and 12 litre tank options.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("RO+UV+UF+TDS,Alkaline option,9L/12L tank,Auto shutoff,2 year warranty").imageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Grand RO Purifier - Aqua Green Agencies Coimbatore").stock(10).minStock(3).displayOrder(2).active(true).build(),
            Product.builder().name("AQUA JADE").description("Elegant slim-design RO purifier with 9-stage purification. Copper-enriched water option available. Ideal for modern kitchens. Available in RO, UV, RO+UV, RO+UV+UF, RO+UV+UF+TDS configurations.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("9-stage RO+UV+UF,Slim design,Copper option,LED indicator,2 year warranty").imageUrl("https://images.unsplash.com/photo-1626863905121-3b0c0ed7b94c?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Jade RO Purifier - Aqua Green Agencies Coimbatore").stock(8).minStock(3).displayOrder(3).active(true).build(),
            Product.builder().name("AQUA MARS").description("Durable domestic RO purifier designed for high TDS water areas. Multi-layer filtration removes fluoride, arsenic, heavy metals. Available with 9-litre SS tank and wall mount stand.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("Multi-stage filtration,High TDS removal,9L tank,Wall/counter mount,1 year warranty").imageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Mars RO Purifier - Aqua Green Agencies Coimbatore").stock(8).minStock(3).displayOrder(4).active(true).build(),
            Product.builder().name("AQUA PUROSIS").description("Premium domestic RO purifier with mineralizer for healthy water. 10-stage purification removes all contaminants while retaining essential minerals. Available in 10 litre tank configuration.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("10-stage purification,Mineralizer,10L tank,TDS controller,2 year warranty").imageUrl("https://images.unsplash.com/photo-1626863905121-3b0c0ed7b94c?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Purosis RO Purifier - Aqua Green Agencies Coimbatore").stock(6).minStock(2).displayOrder(5).active(true).build(),
            Product.builder().name("AQUA 2090").description("Compact and affordable RO purifier ideal for small families. 7-stage filtration with UV disinfection. Wall mountable with auto shutoff. Available in multiple purification configurations with 12 litre tank option.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("7-stage RO+UV,Auto shutoff,12L tank,Wall mountable,1 year warranty").imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=500&h=350&fit=crop&q=85").imageAlt("Aqua 2090 RO Purifier - Aqua Green Agencies Coimbatore").stock(10).minStock(3).displayOrder(6).active(true).build(),
            Product.builder().name("AQUA PEARL").description("Stylish RO purifier with pearl-white finish. Advanced 8-stage purification with UV and UF technology. 9-litre SS tank with auto shutoff. Ideal for families of 3-5 members.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("8-stage RO+UV+UF,Pearl white body,9L SS tank,Auto shutoff,2 year warranty").imageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Pearl RO Purifier - Aqua Green Agencies Coimbatore").stock(8).minStock(3).displayOrder(7).active(true).build(),
            Product.builder().name("AQUA TOUCH").description("Touch-control premium RO purifier with digital TDS display. 8-stage filtration including UV and alkaline filter. 13-litre tank capacity. Smart auto-flush and filter change reminder.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("Touch control,Digital TDS display,8-stage RO+UV,13L tank,Filter reminder,2 year warranty").imageUrl("https://images.unsplash.com/photo-1626863905121-3b0c0ed7b94c?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Touch RO Purifier - Aqua Green Agencies Coimbatore").stock(6).minStock(2).displayOrder(8).active(true).build(),
            Product.builder().name("AQUA GLORY").description("High-capacity domestic RO purifier with 13-litre stainless steel tank. 9-stage purification including UV and UF. Auto-flush system for membrane longevity. Suitable for large families and offices.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("9-stage RO+UV+UF,13L SS tank,Auto-flush,Wall mountable,3 year warranty").imageUrl("https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Glory RO Purifier - Aqua Green Agencies Coimbatore").stock(5).minStock(2).displayOrder(9).active(true).build(),
            Product.builder().name("WHALE 20 LTR").description("Large 20-litre capacity RO purifier ideal for offices and large families. Heavy-duty construction with commercial-grade membrane. 850 LPH output capacity. Available with 20-litre stainless steel tank.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("20L SS tank,850 LPH output,RO+UV+UF+TDS,Auto shutoff,3 year warranty").imageUrl("https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=500&h=350&fit=crop&q=85").imageAlt("Whale 20 Litre RO Purifier - Aqua Green Agencies Coimbatore").stock(5).minStock(2).displayOrder(10).active(true).build(),
            // ── WALL MOUNTING SERIES ────────────────────────────────────────
            Product.builder().name("WALL MOUNTING RO (Basic)").description("Compact wall-mountable RO purifier without storage tank. Direct purification with 9,999 to 14,999 range. Space-saving design ideal for small kitchens. Available in RO, UV, and combined configurations.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("No tank,Wall mountable,Compact design,RO+UV option,1 year warranty").imageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=350&fit=crop&q=85").imageAlt("Wall Mounting RO Purifier Basic - Aqua Green Agencies Coimbatore").stock(8).minStock(3).displayOrder(11).active(true).build(),
            Product.builder().name("WALL MOUNTING RO (Premium)").description("Premium wall-mountable RO purifier with advanced 9-stage filtration. Alkaline and mineralizer options available. Stand and cover accessories available. Suitable for all water conditions in Coimbatore.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("9-stage RO+UV+UF+TDS,Alkaline option,Wall mount,Stand optional,2 year warranty").imageUrl("https://images.unsplash.com/photo-1626863905121-3b0c0ed7b94c?w=500&h=350&fit=crop&q=85").imageAlt("Wall Mounting RO Purifier Premium - Aqua Green Agencies Coimbatore").stock(6).minStock(2).displayOrder(12).active(true).build(),
            // ── AQUA WATER LILLY ────────────────────────────────────────────
            Product.builder().name("AQUA WATER LILLY").description("Elegant countertop and wall-mount RO purifier with lily-white elegant design. 8-stage purification with UV and UF. 9-litre SS tank. Ideal for modern homes and offices seeking style plus purity.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("8-stage RO+UV+UF,Elegant design,9L SS tank,TDS controller,2 year warranty").imageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=500&h=350&fit=crop&q=85").imageAlt("Aqua Water Lilly RO Purifier - Aqua Green Agencies Coimbatore").stock(6).minStock(2).displayOrder(13).active(true).build(),
            // ── NOVA UV ─────────────────────────────────────────────────────
            Product.builder().name("NOVA UV").description("Budget-friendly UV water purifier for areas with good TDS but bacterial contamination. Simple and reliable purification without RO membrane — ideal for borewell and municipal water with acceptable TDS levels.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("DOMESTIC").features("UV purification,No RO membrane,Budget-friendly,Auto shutoff,1 year warranty").imageUrl("https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=500&h=350&fit=crop&q=85").imageAlt("Nova UV Water Purifier - Aqua Green Agencies Coimbatore").stock(8).minStock(3).displayOrder(14).active(true).build(),
            // ── COMMERCIAL PLANTS ───────────────────────────────────────────
            Product.builder().name("Commercial RO 25 LPH").description("Compact commercial RO plant producing 25 litres per hour. Suitable for offices of 20-30 people, clinics, small restaurants. 100L SS tank, digital TDS display, auto-flush system.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("COMMERCIAL").capacityLitres(25).features("25 LPH,100L SS tank,Auto-flush,Digital TDS,1 year warranty").imageUrl("https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=500&h=350&fit=crop&q=85").imageAlt("Commercial RO 25 LPH - Aqua Green Agencies Coimbatore").stock(4).minStock(2).displayOrder(15).active(true).build(),
            Product.builder().name("Commercial RO 50 LPH").description("High-capacity 50 LPH commercial purifier for hotels, hospitals, and large offices. NSF-certified membranes, corrosion-resistant SS body, 200L tank, multi-stage filtration with auto-flush.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("COMMERCIAL").capacityLitres(50).features("50 LPH,200L SS tank,Multi-stage,Auto-flush,2 year warranty").imageUrl("https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=500&h=350&fit=crop&q=85").imageAlt("Commercial RO 50 LPH - Aqua Green Agencies Coimbatore").stock(3).minStock(1).displayOrder(16).active(true).build(),
            Product.builder().name("Industrial RO 100 LPH").description("Industrial-grade 100 LPH RO system for factories, schools, large institutions. Robust SS frame, antiscalant dosing system, FRP pressure vessel, remote monitoring ready.").pricingMode("CONTACT_FOR_PRICE").showPrice(false).isFree(false).category("INDUSTRIAL").capacityLitres(100).features("100 LPH,FRP vessel,Antiscalant dosing,Auto-flush,Remote monitoring,3 year warranty").imageUrl("https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=500&h=350&fit=crop&q=85").imageAlt("Industrial RO 100 LPH - Aqua Green Agencies Coimbatore").stock(2).minStock(1).displayOrder(17).active(true).build()
        ));
        log.info("Seeded {} products", productRepo.count());
    }

    void seedServices() {
        if (serviceRepo.count() > 0) return;
        serviceRepo.saveAll(List.of(
            ServiceItem.builder().name("RO Service / AMC").pricingMode("SHOW_PRICE").description("Complete annual maintenance — filter check, cleaning, sanitisation, membrane inspection and full performance test.").price(new BigDecimal("299")).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=500&h=320&fit=crop&q=85").displayOrder(1).active(true).build(),
            ServiceItem.builder().name("Filter Replacement").pricingMode("SHOW_PRICE").description("Genuine filter cartridges (sediment, pre-carbon, post-carbon) for all brands and models. Only certified parts used.").price(new BigDecimal("199")).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=500&h=320&fit=crop&q=85").displayOrder(2).active(true).build(),
            ServiceItem.builder().name("Leakage Repair").pricingMode("SHOW_PRICE").description("Quick diagnosis and repair of all types of leaks — fittings, tanks, membrane housing and valve leaks. Same-day fix.").price(new BigDecimal("149")).imageUrl("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=500&h=320&fit=crop&q=85").displayOrder(3).active(true).build(),
            ServiceItem.builder().name("New Installation").pricingMode("SHOW_PRICE").description("Professional installation including wall mounting, pipe fitting, connection and first-run performance test. Free with purchase.").price(new BigDecimal("299")).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=500&h=320&fit=crop&q=85").displayOrder(4).active(true).build(),
            ServiceItem.builder().name("Membrane Replacement").pricingMode("SHOW_PRICE").description("Replace worn-out RO membranes with genuine certified 75GPD/100GPD membranes for best filtration performance.").price(new BigDecimal("499")).imageUrl("https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=500&h=320&fit=crop&q=85").displayOrder(5).active(true).build(),
            ServiceItem.builder().name("Water TDS Testing").pricingMode("FREE").description("Free doorstep water quality TDS test. We bring testing equipment and advise the best purification solution for you.").price(BigDecimal.ZERO).imageUrl("https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=500&h=320&fit=crop&q=85").displayOrder(6).active(true).build()
        ));
    }

    void seedGallery() {
        if (galleryRepo.count() > 0) return;
        galleryRepo.saveAll(List.of(
            GalleryItem.builder().title("RO Installation at Residence").description("Successful installation of Aqua Green RO 12L at a customer home in Saravanampatti. Wall-mounted, neat pipe work, same-day installation.").imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=700&h=500&fit=crop&q=85").imageAlt("RO Water Purifier Installation at Home Coimbatore - Aqua Green Agencies Service").category("INSTALLATION").displayOrder(1).active(true).build(),
            GalleryItem.builder().title("Commercial RO Setup — Restaurant").description("50 LPH commercial RO plant installed at a restaurant in RS Puram. Complete plumbing and 200L storage tank done in one day.").imageUrl("https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=700&h=500&fit=crop&q=85").imageAlt("Commercial RO Plant Installation Restaurant Coimbatore - Aqua Green Agencies").category("COMMERCIAL").displayOrder(2).active(true).build(),
            GalleryItem.builder().title("AGA Product Range Display").description("Complete range of domestic, commercial and industrial RO water purifiers at our Neelikonampalayam showroom.").imageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=700&h=500&fit=crop&q=85").imageAlt("Aqua Green Agencies RO Water Purifier Product Range Coimbatore Showroom").category("PRODUCT").displayOrder(3).active(true).build(),
            GalleryItem.builder().title("Filter Replacement Service").description("Expert technician replacing sediment and carbon filters for a customer in Peelamedu. Genuine parts, professional service.").imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=700&h=500&fit=crop&q=85").imageAlt("RO Filter Replacement Service Aqua Green Agencies Technician Coimbatore").category("SERVICE").displayOrder(4).active(true).build(),
            GalleryItem.builder().title("Our Skilled Service Team").description("Meet our trained and certified RO technicians — Murugan, Senthil, and Karthik — serving Coimbatore since 2011.").imageUrl("https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=700&h=500&fit=crop&q=85").imageAlt("Aqua Green Agencies RO Technician Team Coimbatore Expert Water Purifier Service").category("TEAM").displayOrder(5).active(true).build(),
            GalleryItem.builder().title("Industrial RO System — Factory").description("100 LPH industrial RO system commissioned at a manufacturing facility near Coimbatore. SS frame, complete setup.").imageUrl("https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=700&h=500&fit=crop&q=85").imageAlt("Industrial RO Water Treatment Plant Installation Aqua Green Agencies Coimbatore").category("COMMERCIAL").displayOrder(6).active(true).build(),
            GalleryItem.builder().title("AMC Maintenance Service in Progress").description("Annual maintenance service — cleaning, sanitising and performance testing of a residential RO purifier in Ganapathy.").imageUrl("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=700&h=500&fit=crop&q=85").imageAlt("RO AMC Annual Maintenance Service Aqua Green Agencies Coimbatore").category("SERVICE").displayOrder(7).active(true).build(),
            GalleryItem.builder().title("Customer Satisfaction").description("Happy customer after successful RO installation and water quality testing at their home in Ganapathy, Coimbatore.").imageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=700&h=500&fit=crop&q=85").imageAlt("Happy Customer After RO Installation Coimbatore Aqua Green Agencies Service").category("INSTALLATION").displayOrder(8).active(true).build(),
            GalleryItem.builder().title("Genuine Spare Parts Stock").description("Our well-stocked inventory of genuine RO spare parts — membranes, filters, pumps and fittings for all brands.").imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=700&h=500&fit=crop&q=85").imageAlt("Genuine RO Spare Parts Stock Aqua Green Agencies Neelikonampalayam Coimbatore").category("PRODUCT").displayOrder(9).active(true).build()
        ));
        log.info("Seeded gallery");
    }

    void seedAwards() {
        if (awardRepo.count() > 0) return;
        awardRepo.saveAll(List.of(
            Award.builder().title("Best RO Service Provider 2025").organization("Coimbatore Business Excellence Forum").awardYear("2025").description("Awarded for outstanding service quality and customer satisfaction in water purification.").displayOrder(1).active(true).build(),
            Award.builder().title("5000+ Happy Customers").organization("Aqua Green Agencies").awardYear("2024").description("Milestone achieved — serving over 5000 households and businesses across Coimbatore.").displayOrder(2).active(true).build(),
            Award.builder().title("Justdial Trusted Partner").organization("Justdial India").awardYear("2023").description("Verified and trusted business partner on Justdial for consistent 5-star service.").displayOrder(3).active(true).build(),
            Award.builder().title("15 Years of Excellence").organization("Aqua Green Agencies").awardYear("2026").description("Celebrating 15 years of reliable, affordable expert RO water purifier solutions in Coimbatore.").displayOrder(4).active(true).build()
        ));
    }

    void seedEmployees() {
        if (employeeRepo.count() > 0) return;
        employeeRepo.saveAll(List.of(
            Employee.builder().name("Arun Kumar").mobile("9800011111").email("arun@aquagreen.com").role("SUPER_ADMIN").joiningDate(LocalDate.of(2011,1,1)).salary(new BigDecimal("45000")).avatarInitials("AK").active(true).build(),
            Employee.builder().name("Murugan K").mobile("9800022222").email("murugan@aquagreen.com").role("TECHNICIAN").joiningDate(LocalDate.of(2019,3,15)).salary(new BigDecimal("22000")).avatarInitials("MK").active(true).build(),
            Employee.builder().name("Senthil K").mobile("9800033333").email("senthil@aquagreen.com").role("SALES_EXECUTIVE").joiningDate(LocalDate.of(2021,6,1)).salary(new BigDecimal("25000")).avatarInitials("SK").active(true).build(),
            Employee.builder().name("Karthik R").mobile("9800044444").email("karthik@aquagreen.com").role("TECHNICIAN").joiningDate(LocalDate.of(2022,9,10)).salary(new BigDecimal("20000")).avatarInitials("KR").active(true).build(),
            Employee.builder().name("Ravi T").mobile("9800055555").email("ravi@aquagreen.com").role("ACCOUNTANT").joiningDate(LocalDate.of(2020,1,5)).salary(new BigDecimal("28000")).avatarInitials("RT").active(true).build()
        ));
    }

        void seedStock() {
        if (stockRepo.count() > 0) return;
        stockRepo.saveAll(List.of(
            // ── Filters & Cartridges ─────────────────────────────────────
            StockItem.builder().name("EAU Per Carbon Filter").description("Pre-carbon activated carbon block filter for chlorine and chemical removal. 10-inch standard size.").category("FILTER").brand("EAU").unit("PCS").currentStock(50).minStock(10).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("EAU Post Carbon Filter").description("Post-carbon inline filter for taste and odor improvement. Polishes water after RO membrane.").category("FILTER").brand("EAU").unit("PCS").currentStock(50).minStock(10).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("EAU Sediment Filter").description("Sediment spun filter removes sand, mud, rust and suspended particles above 5 micron. 10-inch.").category("FILTER").brand("EAU").unit("PCS").currentStock(60).minStock(10).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("KEMFLOW Spun Filter").description("High-quality polypropylene spun sediment filter. Removes suspended particulates. 10-inch 5-micron rating.").category("FILTER").brand("KEMFLOW").unit("PCS").currentStock(40).minStock(10).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Pentaiyar Spun Filter").description("Pentaiyar brand PP spun filter for sediment removal. Compatible with all standard housings. 10-inch.").category("FILTER").brand("PENTAIYAR").unit("PCS").currentStock(40).minStock(10).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Healthy Carbon Filter").description("Healthy brand granular activated carbon filter for chlorine and taste improvement.").category("FILTER").brand("HEALTHY").unit("PCS").currentStock(35).minStock(8).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Healthy Sediment Filter").description("Healthy brand sediment spun filter. Removes rust, sand and suspended particles up to 5 micron.").category("FILTER").brand("HEALTHY").unit("PCS").currentStock(35).minStock(8).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("20 Inch Spun Slim Filter").description("Slim 20-inch spun PP sediment filter for high-flow housings. Used in commercial RO systems.").category("FILTER").brand("GENERIC").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("UF Mineral 4 Inch Filter").description("4-inch UF mineral filter for remineralizing purified water. Adds calcium, magnesium and trace minerals.").category("FILTER").brand("GENERIC").unit("PCS").currentStock(15).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Mineral Cartridge").description("Inline mineral cartridge adds healthy minerals back into RO purified water for better taste and health.").category("FILTER").brand("GENERIC").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Eau Candle 9 Inch Filter").description("9-inch candle filter with ceramic and carbon media. For use in specific housing types.").category("FILTER").brand("EAU").unit("PCS").currentStock(25).minStock(8).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Free Filter Housing").description("Standard 10-inch filter housing for pre/post carbon and sediment filters. Transparent bowl.").category("HOUSING").brand("GENERIC").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            // ── Membranes ────────────────────────────────────────────────
            StockItem.builder().name("Merit 80 GPD Membrane").description("Merit brand 80 GPD (gallons per day) RO membrane. Compatible with most domestic RO purifiers. High rejection rate 99%.").category("MEMBRANE").brand("MERIT").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Merit 100 GPD Membrane").description("Merit brand 100 GPD RO membrane for higher output systems. 99% TDS rejection. Compatible with most brands.").category("MEMBRANE").brand("MERIT").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Ottya 80 GPD Membrane").description("Ottya brand 80 GPD thin-film composite RO membrane. High rejection and long life. Suitable for TDS up to 2000 ppm.").category("MEMBRANE").brand("OTTYA").unit("PCS").currentStock(15).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Ottya 100 GPD Membrane").description("Ottya brand 100 GPD high-output RO membrane for domestic and semi-commercial systems. 99% TDS rejection.").category("MEMBRANE").brand("OTTYA").unit("PCS").currentStock(15).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            // ── Power Supply (SMPS) ──────────────────────────────────────
            StockItem.builder().name("Shine SMPS 1.5 Amps 24V").description("Shine brand 24V 1.5A SMPS power adapter for domestic RO purifiers. Powers booster pump and solenoid valve.").category("ELECTRICAL").brand("SHINE").unit("PCS").currentStock(15).minStock(5).imageUrl("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Shine SMPS 2.5 Amps 24V").description("Shine brand 24V 2.5A SMPS power adapter for commercial RO systems. Higher current for bigger pumps.").category("ELECTRICAL").brand("SHINE").unit("PCS").currentStock(10).minStock(3).imageUrl("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop&q=85").active(true).build(),
            // ── Solenoid Valves ──────────────────────────────────────────
            StockItem.builder().name("SV Hero 24V Solenoid Valve").description("Hero brand 24V solenoid valve (SV) for automatic water control in RO systems. High durability, long life.").category("ELECTRICAL").brand("HERO").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("SV Hero 36V Solenoid Valve").description("Hero brand 36V solenoid valve for specific RO purifier models requiring 36V operation.").category("ELECTRICAL").brand("HERO").unit("PCS").currentStock(15).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("SV SLC 24V Solenoid Valve").description("SLC brand 24V solenoid valve. Precision flow control for RO auto-shutoff systems.").category("ELECTRICAL").brand("SLC").unit("PCS").currentStock(15).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("SV SLC 36V Solenoid Valve").description("SLC brand 36V solenoid valve for premium RO purifier models.").category("ELECTRICAL").brand("SLC").unit("PCS").currentStock(10).minStock(3).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            // ── Connectors & Fittings ────────────────────────────────────
            StockItem.builder().name("Pipe Roll 1/4 Inch").description("1/4 inch (6mm) clear LDPE pipe for RO water connections. Per metre supply for flexible plumbing.").category("PLUMBING").brand("GENERIC").unit("MTR").currentStock(200).minStock(50).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Pipe Roll 3/8 Inch").description("3/8 inch (10mm) pipe for drain and inlet connections in RO systems. Per metre supply.").category("PLUMBING").brand("GENERIC").unit("MTR").currentStock(150).minStock(50).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Handle Plastic 1/4 Blue").description("Blue handle plastic ball valve for 1/4 inch pipe. Manual shutoff for RO input water line.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(30).minStock(10).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Nipple Brass Input").description("Brass nipple input connector for connecting RO system to main water supply line.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(30).minStock(10).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("FR-450 Green Connector").description("FR-450 green flow restrictor for controlling drain water ratio in RO systems. Essential for membrane longevity.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(25).minStock(8).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Double Lock 1/4 Elbow").description("Double-lock push-fit 1/4 inch elbow connector. Quick connect fitting for 90-degree pipe direction change.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(50).minStock(15).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Elbow 1/4 Inch").description("Standard 1/4 inch push-fit elbow for RO water line routing. Quick connect, no tools required.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(60).minStock(20).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Elbow 1/8 Inch").description("1/8 inch elbow connector for smaller diameter tubes and fittings in compact RO systems.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(40).minStock(10).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Elbow 3/8 In Thread 1/4").description("3/8 inch threaded to 1/4 inch push-fit elbow adapter. Connects drain line to different thread sizes.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(30).minStock(10).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("T Elbow 1/4 3Side").description("3-way T-connector for 1/4 inch pipe. Splits or combines water lines in RO purifier plumbing.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(30).minStock(10).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Pump Elbow 1/4").description("Pump-specific 1/4 inch elbow connector for connecting tubes directly to booster pump inlet/outlet.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(25).minStock(8).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Union Body Input Connector").description("Union body input connector for easy disconnect maintenance of RO filter housings and membrane vessels.").category("PLUMBING").brand("GENERIC").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Float Cherry Switch D").description("Cherry-type float switch for RO tank level control. Automatically shuts off pump when tank is full.").category("ELECTRICAL").brand("GENERIC").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop&q=85").active(true).build(),
            // ── Clamps ───────────────────────────────────────────────────
            StockItem.builder().name("C Clamp 2 Side").description("2-sided C clamp for securing RO filter housings and components to the mounting bracket or wall.").category("HARDWARE").brand("GENERIC").unit("PCS").currentStock(30).minStock(10).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("C Clamp 2.5 Inch").description("2.5-inch C clamp for larger filter housings. Stainless steel finish for durability.").category("HARDWARE").brand("GENERIC").unit("PCS").currentStock(25).minStock(8).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("C Clamp 2.5x2 Inch").description("2.5x2 inch double-grip C clamp for heavy-duty mounting of commercial RO components.").category("HARDWARE").brand("GENERIC").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("X C Clamp 2.5x2.5 Inch").description("Cross-type C clamp 2.5x2.5 inch for corner or cross-mounting of RO components and pipes.").category("HARDWARE").brand("GENERIC").unit("PCS").currentStock(15).minStock(5).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            // ── UV Components ────────────────────────────────────────────
            StockItem.builder().name("UV Choke HD").description("Heavy-duty UV choke (ballast) for UV lamp operation in water purifiers. Controls current to UV tube.").category("ELECTRICAL").brand("GENERIC").unit("PCS").currentStock(15).minStock(5).imageUrl("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("UV Barrel").description("UV barrel housing for UV lamp assembly in domestic water purifiers. Stainless steel inner chamber.").category("HOUSING").brand("GENERIC").unit("PCS").currentStock(10).minStock(3).imageUrl("https://images.unsplash.com/photo-1563453392212-326f5e854473?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("UV Tube Lamp").description("UV-C germicidal lamp tube for water purifiers. Destroys bacteria, viruses and other pathogens. Needs annual replacement.").category("ELECTRICAL").brand("GENERIC").unit("PCS").currentStock(20).minStock(5).imageUrl("https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&h=300&fit=crop&q=85").active(true).build(),
            // ── Quick Connect Inserts ────────────────────────────────────
            StockItem.builder().name("Aqua Crux Blue Insert").description("Aqua Crux blue push-in insert for quick-connect fittings. Ensures leak-free connection for 1/4 inch pipes.").category("PLUMBING").brand("AQUA CRUX").unit("PCS").currentStock(50).minStock(15).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Aqua Krown Insert").description("Aqua Krown brand quick-connect insert for tube fittings. High pressure rated for RO water systems.").category("PLUMBING").brand("AQUA KROWN").unit("PCS").currentStock(40).minStock(10).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build(),
            StockItem.builder().name("Aqua Swift Transparent Insert").description("Transparent Aqua Swift quick-connect insert. Allows visual confirmation of pipe seating. For 1/4 inch tubes.").category("PLUMBING").brand("AQUA SWIFT").unit("PCS").currentStock(40).minStock(10).imageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=400&h=300&fit=crop&q=85").active(true).build()
        ));
        log.info("Seeded {} stock items", stockRepo.count());
    }

    void seedBlogs() {
        if (blogRepo.count() > 0) return;
        blogRepo.saveAll(List.of(
            Blog.builder().title("Best RO Water Purifier Service in Coimbatore 2026").slug("best-ro-service-coimbatore-2026").content("<h2>Why Regular RO Service Matters</h2><p>Annual servicing ensures filters are replaced, the membrane is clean, and output water meets safety standards. Our technicians check all filtration stages and test TDS levels.</p>").excerpt("Learn why regular RO service is critical and what Aqua Green Agencies checks during a service visit.").featuredImageUrl("https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=800&h=400&fit=crop&q=85").seoTitle("Best RO Service Coimbatore 2026 | Aqua Green Agencies").seoDescription("Professional RO service in Coimbatore. 15+ years experience. Call 09054617008.").status("PUBLISHED").author("Arun Kumar").publishedAt(LocalDateTime.now().minusDays(15)).createdAt(LocalDateTime.now().minusDays(15)).updatedAt(LocalDateTime.now().minusDays(15)).build(),
            Blog.builder().title("RO vs UV Water Purifier — Which is Better for Coimbatore?").slug("ro-vs-uv-water-purifier-coimbatore").content("<h2>Understanding Coimbatore Water</h2><p>Coimbatore gets water from Siruvani River. For TDS above 200 ppm, RO is the right choice. For bacterial-only issues with low TDS, UV is sufficient.</p>").excerpt("Compare RO and UV purifiers to find the best fit for Coimbatore's water quality.").featuredImageUrl("https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=800&h=400&fit=crop&q=85").seoTitle("RO vs UV Water Purifier Coimbatore | Which is Better?").seoDescription("Compare RO vs UV purifiers for Coimbatore. Expert guide by Aqua Green Agencies.").status("PUBLISHED").author("Arun Kumar").publishedAt(LocalDateTime.now().minusDays(8)).createdAt(LocalDateTime.now().minusDays(8)).updatedAt(LocalDateTime.now().minusDays(8)).build(),
            Blog.builder().title("5 Signs Your RO Purifier Needs Immediate Service").slug("signs-ro-purifier-needs-service").content("<h2>1. Slow Water Flow</h2><p>Membrane or filters are clogged.</p><h2>2. Bad Taste or Smell</h2><p>Post-carbon filter is exhausted.</p>").excerpt("5 warning signs it is time for professional RO service.").featuredImageUrl("https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&h=400&fit=crop&q=85").seoTitle("5 Signs RO Purifier Needs Service | Aqua Green Agencies Coimbatore").seoDescription("5 signs your RO purifier needs service. Tips from Coimbatore's trusted service provider.").status("DRAFT").author("Murugan K").createdAt(LocalDateTime.now().minusDays(3)).updatedAt(LocalDateTime.now().minusDays(3)).build()
        ));
    }
}

// NOTE: This line intentionally left blank - template and communication seeding
// is handled by the TemplateSeedConfig class below
